phrase:
  access_token: 96c491babf683d0db9de9588e5ed747e06816f5c0d371f76f7e4eb67b05a4a51
  project_id: 65d53210ed0ddb87b8ae98a83370ca9d
  push:
    sources:
    - file: ./source/en_US.js
      params:
        file_format: ember_js
        update_translations: true
        locale_id: f001dfc4dba6b84e9220d8976938631d
  pull:
    targets:
    - file: ./locales/<locale_name>.json
      params:
        file_format: node_json
