{
  "about": "About",
  "about_us": "About Us",
  "about_us_one": "Cras consequat iaculis lorem, id vehicula erat mattis quis. Vivamus laoreet velit justo, in ven e natis purus pretium sit amet. Praesent lectus tortor, tincidu nt in consectetur vestibulum, ultrices nec neque. Praesent nec sagittis mauris. Fusce convallis nunc neque. Integer egestas aliquam interdum. Nulla ante diam, interdum nec tempus eu, feugiat vel erat.Cras consequat iaculis lorem, id vehicula erat mattis quis.Cras consequat iaculis lorem, id vehicula erat mattis. Integer egestas aliquam interdum. Nulla ante diam,",
  "about_us_two": "lorem,Cras consequat iaculis id vehicula erat mattis quis. Vivamus laoreet velit justo, in ven e natis purus pretium sit amet. Praesent lectus tortor, tincidu nt in consectetur vestibulum, ultrices nec neque. Praesent nec sagittis mauris. Fusce convallis nunc neque. Integer egestas aliquam interdum. Nulla ante diam, interdum nec tempus eu, feugiat vel erat.Cras consequat iaculis lorem, id vehicula erat mattis quis.Cras consequat iaculis lorem, id vehicula erat mattis.",
  "add_3rd_string": "Now it should be correct!",
  "add_4th_string": "Now it is the 4th new string!",
  "add_from_local": "a string from my local env!",
  "add_more_strings": "This is another new string",
  "added_from_git": "This new string is added git",
  "advantages_text": "With the In-context Editor, clients like Fair Trade and Jimdo are able to minimize errors by giving translators insight into the context of the translation and letting them edit the content right on the spot.",
  "advantages_title": "Minimize errors",
  "begin_placeholder": "Start date",
  "blog": "Blog",
  "categories": "Categories",
  "clients_title": "Don’t worry, we support your tech stack:",
  "ColorPicker.btn:cancel": "Cancel",
  "ColorPicker.btn:clear": "Clear",
  "ColorPicker.btn:save": "Save",
  "comments": "Comments",
  "cons_iaculis": "Consectetur adipiscing iaculis",
  "contact": "Contact",
  "contact_s": "Contact",
  "copyright": "Copyright",
  "cras": "Cras consequat iaculis lorem",
  "cras_consequat": "Cras consequat",
  "cras_consequat_ds": "Cras consequat iaculis lorem, id vehicula erat mattis quis. Vivamus laoreet velit justo, in ven e natis purus.",
  "critics": "Critics",
  "criticsinput": "Please directly @ name / job number. Up to 5 people can be invited",
  "cultivation_home": "cultivation",
  "cum_et": "Cum sociis natoque penatibus et magnis",
  "customer": "Customer",
  "customerinput": "Please describe the customer you serve, internal customer direct @ name / job number",
  "customerrequired": "Please describe the customers you serve",
  "dashboard.analysis.name": "From Page",
  "dashboard.basic.name": "Detail Page",
  "dashboard.name": "Workbench",
  "dashboard.workplace.name": "Search List Page",
  "date": "Start and end date",
  "daterequired": "Please select a start and end date",
  "describe": "Describe",
  "describeinput": "Please enter your phased work objectives",
  "descriptionrequired": "Please enter the target description",
  "disclosure": "Disclosure",
  "disclosuredesc": "Customers and invited reviewers are shared by default",
  "dolor_nunc_vule": "Dolor nunc vule",
  "dolor_nunc_vule_ds": "Cras consequat iaculis lorem, id vehicula erat mattis quis. Vivamus laoreet velit justo, in ven e natis purus.",
  "dolor_putateulr": "Dolor nunc vule putateulr",
  "dolor_putateulr_desc": "Cras consequat iaculis lorem, id vehicula erat mattis quis. Vivamus laoreet velit justo, in ven e natis purus.Praesent nec sagittis mauris. Fusce convallis nunc neque.Integer egestas.Vivamus laoreet velit justo",
  "dolor_putateulr_s": "Dolor nunc vule putateulr",
  "dolor_putateulr_s_desc": "Cras consequat iaculis lorem, id vehicula erat mattis quis. Vivamus laoreet velit justo, in ven e natis purus.Praesent nec sagittis mauris. Fusce convallis nunc neque.Integer egestas.Vivamus laoreet velit justo",
  "dolor_putateulr_t": "Dolor nunc vule putateulr",
  "dolor_putateulr_t_desc": "Cras consequat iaculis lorem, id vehicula erat mattis quis. Vivamus laoreet velit justo, in ven e natis purus.Praesent nec sagittis mauris. Fusce convallis nunc neque.Integer egestas.Vivamus laoreet velit justo",
  "Empty.description": "No Data",
  "end_placeholder": "End date",
  "form.basic.name": "baseis",
  "fusce_suscipit": "Fusce suscipit",
  "global.placeholder": "Please select",
  "hero_description": "Click the pen icon on the text and interact with our In-context Editor in the lower half of the screen. Change the original text or click the flag icon to change languages. Try it out!",
  "hero_link_code": "See source code",
  "hero_link_docs": "View our documentation",
  "hero_title": "Translate a Website While Looking at It",
  "home": "Home",
  "Icon.icon": "icon",
  "inte_lorem": "Integer molestie lorem",
  "integer_molest": "Integer molest",
  "integrate_text": "The Phrase In-context Editor can be integrated within almost any web application and provides you with the ability to translate content directly on your site. Now, you’re able to see the translations right where they belong.",
  "integrate_title": "Integrate the Phrase In-context Editor into your existing application",
  "latest_news": "Latest News",
  "locale": "en",
  "lock": "Lock",
  "login_desc": "Phrase In-context Editor demo",
  "lorem_id": "lorem,Cras consequat iaculis id vehicula",
  "lorem_one": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  "lorem_sit": "Lorem ipsum dolor sit",
  "lorem_three": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  "lorem_two": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  "metrics": "Metrics",
  "metricsinput": "Please enter a measurement",
  "Modal.cancelText": "Cancel",
  "Modal.justOkText": "OK",
  "Modal.okText": "OK",
  "new_title_one": "Dolor nunc vule putateulr",
  "new_title_one_desc": "Praesent vestim molestie lacus. Aenean nonummy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  "new_title_one_time": "March 23rd, 2015",
  "new_title_three": "Dolor nunc vule putateulr",
  "new_title_three_desc": "Praesent vestim molestie lacus. Aenean nonummy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  "new_title_three_time": "March 23rd, 2015 ",
  "new_title_two": "Dolor nunc vule putateulr",
  "new_title_two_desc": "Praesent vestim molestie lacus. Aenean nonummy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  "new_title_two_time": "March 23rd, 2015 ",
  "newly_added_section": "I'm an update",
  "nunc_vule_put": "nunc vule put",
  "nunc_vule_put_ds": "Cras consequat iaculis lorem, id vehicula erat mattis quis. Vivamus laoreet velit justo, in ven e natis purus.",
  "our_latest_works": "Our Latest Works",
  "page_about_about_h1": "About",
  "page_about_advantages": "Advantages",
  "page_about_advantages_1": "Praesent vestim molestie lacus.",
  "page_about_advantages_2": "Cras consequat iaculis lorem",
  "page_about_advantages_3": "Consectetur adipiscing iaculis",
  "page_about_advantages_4": "Lorem ipsum dolor sit",
  "page_about_advantages_5": "Cum sociis natoque penatibus et magnis",
  "page_about_advantages_6": "Integer molestie lorem",
  "page_about_advantages_7": "lorem,Cras consequat iaculis id vehicula",
  "page_about_cultivation_about": "cultivation",
  "page_about_david_austin": "David Austin",
  "page_about_david_austin_desc": "Donec pellentesque lacus at magna porttitor pulvinar. Morbi risus lorem; sollicitudin sit",
  "page_about_eva_adamson": "Eva Adamson",
  "page_about_eva_adamson_desc": "Donec pellentesque lacus at magna porttitor pulvinar. Morbi risus lorem; sollicitudin sit",
  "page_about_jack": "Jack",
  "page_about_jack_desc": "Donec pellentesque lacus at magna porttitor pulvinar. Morbi risus lorem; sollicitudin sit",
  "page_about_john_anderson": "JOHN ANDERSON",
  "page_about_john_anderson_desc": "suadaorcnec sit amet eroorem ipsum dol. Or sit amt consc tetuer aiing elit. Mauris fermentum tumagna. Sed laoreet aliquam leo. Ut te dolor dapibus eget elentu vel cursus eleifend elit. Aenean auctor wrna. Aliqua volutpat. Duis ac turpis. Integer rutrum ante eu lacuest um liberoisl porta vel sceleisque eget malesuada at neque. Vivam nibhus metus",
  "page_about_nulla_desc": "Nulla nec aliquam est! Vestibulum ultrices bibendum condimentum. Donec pellentesque lacus at magna porttitor pulvinar. Morbi risus lorem; sollicitudin sit amet lacinia vitae; dictum ut augue. Nulla dapibus consequat dolor in tristique. Donec quis dictum magna. Integer vulputate tortor at augue mollis eu cursus sapien feugiat. Proin porttitor malesuada tincidunt. Nulla consectetur felis sem, a adipiscing est. Donec at risus diam; ut fermentum neque. Maecenas dapibus molestie nisl.gravida cursus nibh. In at metus aliquet, gravida nunc eget, lacinia purus. Sed a mi mollis, faucibus erat. Vivamus at facilisis tortor. Integer condimentum lectus sit amet .sagittis, nisl magna sodales eros, ut feugiat velit velit non turpis.nisl magna sodales eros, ut feugiat velit velit non turpis.ipsum dolor sit amet, consectetur adipiscing elit.ectus sit amet .",
  "page_about_nulla_title": "Nulla Dapibus Consequat Dolor In Tristique. Donec Quis.",
  "page_about_olivia_grosh": "OLIVIA GROSH",
  "page_about_olivia_grosh_desc": "sit amet eroorem ipsum dol. Or sit amt consc tetuer aiing elit. Mauris fermentum tumagna. Sed laoreet aliquam leo. Ut te dolor dapibus eget elentu vel cursus eleifend elit. Aenean auctor wrna. Aliqua volutpat. Duis ac turpis. Integer rutrum ante eu lacuest um liberoisl porta vel sceleisque eget malesuada at neque. Vivam nibhus metus",
  "page_about_our_team": "Our Team",
  "page_about_testimonials": "Testimonials",
  "page_blog_back_to_home": "Back to Home",
  "page_blog_cultivation_blog": "cultivation",
  "page_blog_dead_link": "THIS LINK DEAD LINK",
  "page_contact_contact_us": "Contact Us",
  "page_contact_cultivation_contact": "cultivation",
  "page_contact_email": "Email :",
  "page_contact_message": "Message :",
  "page_contact_name": "Name :",
  "page_contact_send": "Send",
  "page_contact_subject": "Subject :",
  "page_detail_abstract": "Abstract",
  "page_detail_by": "By:",
  "page_detail_disabled": "Lucy",
  "page_detail_document_type": "Document Type",
  "page_detail_export": "Export XLSX",
  "page_detail_full_text": "Full Text",
  "page_detail_full_text_link": "Full Text Link",
  "page_detail_import": "Import XLSX",
  "page_detail_exportcsv": "Export CSV",
  "page_detail_importcsv": "Import CSV",
  "page_detail_title": "How to Write an Abstract",
  "page_detail_subtitle": "Steps and Samples",
  "page_detail_text_body": "Body",
  "page_detail_abstract_text": "An abstract is a short summary of a longer work (such as a dissertation or research paper).",
  "page_detail_body_p1": "An abstract is usually around 150–300 words, but there’s often a strict word limit, so make sure to check the requirements of the university or journal.",
  "page_detail_body_p2": "In a dissertation or thesis, include the abstract on a separate page, after the title page and acknowledgements but before the table of contents.",  
  "page_detail_indexed": "Indexed",
  "page_detail_issue": "Issue",
  "page_detail_lucy": "Jack",
  "page_detail_page": "Page",
  "page_detail_published": "Published",
  "page_detail_vaccimonitor": "Vaccimonitor",
  "page_detail_volume": "Volume",
  "page_detail_yiminghe": "Mark",
  "page_list_activeuser": "Active User",
  "page_list_application": "Application",
  "page_list_article": "Article",
  "page_list_category": "Category",
  "page_list_category1": "category 1",
  "page_list_category2": "category 2",
  "page_list_degree": "Degree",
  "page_list_excellent": "excellent",
  "page_list_justlook": "justlook",
  "page_list_open": "Open",
  "page_list_other": "Other",
  "page_list_owner": "Owner",
  "page_list_project": "Project",
  "page_list_search": "Search",
  "page_list_search_placeholder": "search input...",
  "page_list_unlimited": "unlimited",
  "page_login_account": "Account",
  "page_login_admin_placeholder": "Please enter the account name",
  "page_login_admin_tip": "Please enter the account name",
  "page_login_auto": "Auto Login",
  "page_login_btn": "Login",
  "page_login_desc": "Phrase In-context Editor demo",
  "page_login_forget": "Forget password",
  "page_login_mobile": "Mobile",
  "page_login_password_placeholder": "Please input a password",
  "page_login_password_tip": "Please input a password",
  "page_login_title": "Phrase Admin Demo",
  "page_products_cultivation_products": "cultivation",
  "page_products_products_title": "Products",
  "page_services_cultivation_services": "cultivation",
  "page_services_lorem_dolor": "Harvesting",
  "page_services_lorem_dolor_desc": "Provide leasing service of combine harvester to reduce labor and realize rapid harvest and warehousing of crops",
  "page_services_our_services": "cultivation service",
  "page_services_pamet_erosorem": "Picking",
  "page_services_pamet_erosorem_desc": "For operations that are difficult to be mechanized, such as picking, provide labor dispatch services to meet the employment needs in peak periods",
  "page_services_read_more": "read more",
  "page_services_solor_sit_amet": "Selling",
  "page_services_solor_sit_amet_desc": "Our company sells agricultural products on a commission basis with rich channels and reasonable prices.",
  "PageHeader.back": "Back",
  "Pagination.items_per_page": "/ page",
  "Pagination.jump_to": "Go to",
  "Pagination.jump_to_confirm": "confirm",
  "Pagination.next_3": "Next 3 Pages",
  "Pagination.next_5": "Next 5 Pages",
  "Pagination.next_page": "Next Page",
  "Pagination.page": "page",
  "Pagination.prev_3": "Previous 3 Pages",
  "Pagination.prev_5": "Previous 5 Pages",
  "Pagination.prev_page": "Previous Page",
  "partially": "Partially",
  "Popconfirm.cancelText": "Cancel",
  "Popconfirm.okText": "OK",
  "praesent_vestim": "Praesent vestim molestie lacus.",
  "private": "Private",
  "products": "Products",
  "project": "Project",
  "prompt_text": "Prompt text",
  "public": "Public",
  "sagittis_magna": "sagittis magna",
  "save": "Save",
  "services": "Services",
  "submit": "Submit",
  "Table.collapse": "Collapse row",
  "Table.expand": "Expand row",
  "Table.filterConfirm": "OK",
  "Table.filterReset": "Reset",
  "Table.filterTitle": "Filter menu",
  "Table.selectAll": "Select current page",
  "Table.selectInvert": "Invert current page",
  "Table.sortTitle": "Sort",
  "test": "test",
  "Text.copied": "Copied",
  "Text.copy": "Copy",
  "Text.edit": "Edit",
  "Text.expand": "Expand",
  "TimePicker.placeholder": "Select time",
  "title": "Title",
  "titleinput": "Give the target a name",
  "titlerequired": "Please enter a title",
  "Transfer.itemsUnit": "items",
  "Transfer.itemUnit": "item",
  "Transfer.searchPlaceholder": "Search here",
  "typerequired": "Please enter a measurement",
  "upcome_events": "upcome events",
  "Upload.downloadFile": "Download file",
  "Upload.previewFile": "Preview file",
  "Upload.removeFile": "Remove file",
  "Upload.uploadError": "Upload error",
  "Upload.uploading": "Uploading...",
  "vule_dolor_nunc": "vule Dolor nunc",
  "vule_dolor_nunc_ds": "Cras consequat iaculis lorem, id vehicula erat mattis quis. Vivamus laoreet velit justo, in ven e natis purus.",
  "weight": "Weight"
}