{
	"page_list_category": "Category",
	"page_list_category1": "category 1",
	"page_list_category2": "category 2",
	"page_list_justLook": "justlook",
	"page_list_owner": "owner",
	"page_list_other": "Other",
	"page_list_activeUser": "Active User",
	"page_list_unlimited": "unlimited",
	"page_list_degree": "Degree",
	"page_list_excellent": "excellent",
	"page_list_open": "Open",
	"page_login_title":"Phrase Admin Demo",
	"page_login_desc":"Phrase In-context Editor demo",
	"page_login_account":"Account",
	"page_login_mobile":"Mobile",
	"page_login_admin_tip":"Please enter the account name",
	"page_login_password_tip":"Please input a password",
	"page_login_cmd":"Get verification code",
	"page_login_auto":"Auto Login",
	"page_login_forget":"Forget password",
	"page_login_btn":"Login",
	"mobile_number":"mobile number",
	"page_login_password_placeholder":"password",
	"page_login_admin_placeholder":"admin",
	"page_detail_vaccimonitor":"Vaccimonitor",
	"page_detail_volume":"Volume",
	"page_detail_issue":"Issue",
	"begin_placeholder":"Start date",
	"end_placeholder":"End date",
	"page_detail_page":"Page",
	"page_detail_published":"Published",
	"page_detail_indexed":"Indexed",
	"page_detail_document_type":"Document Type",
	"page_detail_by":"By",
	"page_detail_export":"Export",
	"page_detail_import":"Import",
	"page_detail_abstract":"Abstract",
	"page_detail_full_text":"Full Text",
	"page_detail_full_text_link":"Full Text Links",
	"page_detail_lucy":"",
	"page_detail_disabled":"disabled",
	"page_detail_yiminghe":"",
	"page_list_article":"article",
	"page_list_application":"application",
	"project":"project",
	"page_list_search":"Search",
	"page_list_search_placeholder":"search input...",
	"customerInput": "Please describe the customer you serve, internal customer direct @ name / job number",
	"critics": "Critics",
	"criticsInput": "Please directly @ name / job number. Up to 5 people can be invited",
	"weight": "Weight",
	"disclosure": "Disclosure",
	"disclosureDesc": "Customers and invited reviewers are shared by default",
	"public": "Public",
	"partially": "Partially",
	"private": "Private",
	"submit": "Submit",
	"save": "Save",
	"colleague1": "Colleague 1",
	"colleague2": "Colleague 2",
	"colleague3": "Colleague 3",
	"titleRequired":"Please enter a title",
	"dateRequired":"Please select a start and end date",
	"descriptionRequired":"Please enter the target description",
	"typeRequired":"Please enter a measurement",
	"customerRequired":"Please describe the customers you serves",
	"prompt_text":"",
	"title":"",
	"titleInput":"",
	"date":"",
	"describe":"",
	"describeInput":"",
	"metrics":"",
	"metricsInput":"",
	"customer":""
}
